services:
  web:
    image: flutterflirt/templeapp:latest
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 on the host
    restart: unless-stopped
    networks:
      - app-network
    #nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs # Mount directory for SSL certificates

    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

#nginx network config
networks:
  app-network:
    driver: bridge
