name: Build and Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust Node version as required

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t flutterflirt/goshala:latest .

      - name: Push Docker image
        run: |
          docker push flutterflirt/goshala:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Ubuntu Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # Navigate to the directory with your docker-compose.yml file
            cd /home/ubuntu/goshala

            # Ensure Docker Compose is stopped, then pull and start the latest image
            docker compose down
            docker system prune -af
            docker compose up -d
